spring:
  application:
    name: nganhang-pt
  
  # Disable JPA auto-configuration (we'll use JDBC directly for stored procedures)
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  
  # SQL Server - NGANHANG (Main Database - Chỉ kết nối DB chính)
  # DB chính sẽ tự động truy vấn các phân mảnh thông qua Linked Server
  # Kết nối qua VPN/mạng ảo đến IP 10.241.78.94
  datasource:
    jdbc-url: jdbc:sqlserver://10.241.78.94;databaseName=NGANHANG;encrypt=true;trustServerCertificate=true
    username: HTKN
    password: '123456'
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

# Cấu hình các phân mảnh (Fragment Configuration)
app:
  fragments:
    username: HTKN
    password: '123456'
    servers:
      - name: 'HCM-LAPT-001\SQLSRV_NH01'
        url: jdbc:sqlserver://10.241.78.94:1440;databaseName=NGANHANG;encrypt=true;trustServerCertificate=true
      - name: 'HCM-LAPT-001\SQLSRV_NH02'
        url: jdbc:sqlserver://10.241.78.94:1441;databaseName=NGANHANG;encrypt=true;trustServerCertificate=true
      - name: 'HCM-LAPT-001\SQLSRV_NH03'
        url: jdbc:sqlserver://10.241.78.94:1443;databaseName=NGANHANG;encrypt=true;trustServerCertificate=true
